
- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - nginx
    - certbot

- name: Create nginx file distribution directory
  file:
    path: "/var/www/html"
    state: directory
    owner: "nginx"
    group: "nginx"

- name: Copy nginx main config
  ansible.builtin.template:
    dest: "/etc/nginx/nginx.conf"
    src: "nginx.conf.j2"
    mode: "0755"
 
- name: Copy nginx conf.d configs
  ansible.builtin.template:
    dest: "/etc/nginx/conf.d/{{ item }}.conf"
    src: "{{ item }}.conf.j2"
    mode: "0755"
  with_items: 
    - main

- name: Make sure nginx is started and enabled
  ansible.builtin.sysvinit:
      name: "{{ item }}"
      state: started
      enabled: yes
  with_items:
    - nginx
