

- name: Fruitywifi | Download and unarchive 
  ansible.builtin.unarchive:
    src: https://github.com/xtr4nge/FruityWifi/archive/refs/heads/master.zip
    dest: /opt/
    remote_src: yes

- name: Fruitywifi | Chmod and run fruitywifi install-FruityWiFi.sh
  command:
    cmd: chmod +x /opt/FruityWifi-master/install-FruityWiFi.sh; bash /opt/FruityWifi-master/install-FruityWiFi.sh

- name: Fruitywifi | Make sure Fruitywifi and php5-fpm is started and enabled
  ansible.builtin.sysvinit:
      name: "{{ item }}"
      state: started
      enabled: yes
  with_items:
    - fruitywifi
    - php5-fpm
