

- name: download and unarchive 
  ansible.builtin.unarchive:
    src: https://github.com/donutoperator/FruityWifi/archive/refs/heads/master.zip
    dest: /opt/
    remote_src: yes

- name: chmod and run fruitywifi install-FruityWiFi.sh
  command:
    cmd: chmod +x /opt/FruityWifi-master/install-FruityWiFi.sh; bash /opt/FruityWifi-master/install-FruityWiFi.sh

- name: copy configs
  ansible.builtin.copy:
    dest: "/usr/share/fruitywifi/conf/{{ item }}"
    src: "{{ item }}"
  with_items: 
    - dnsmasq.conf
    - hostapd-secure.conf
    - hostapd.conf
    - pool-ssid.conf
    - pool-station.conf
    - resolv.conf
    - spoofhost.conf
    - ssid.conf
    - wpa_supplicant.conf

- name: make sure nginx and php8.2-fpm is started and enabled
  ansible.builtin.sysvinit:
      name: "{{ item }}"
      state: started
      enabled: yes
  with_items:
    - nginx
    - php8.2-fpm
