

- name: Unarchive downloaded fruitywifi
  ansible.builtin.unarchive:
    src: https://github.com/xtr4nge/FruityWifi/archive/refs/heads/master.zip
    dest: /opt/
    remote_src: yes

- name: chmod and run fruitywifi install-FruityWiFi.sh
  command:
    cmd: chmod +x install-FruityWiFi.sh; bash install-FruityWiFi.sh
    chdir:  /opt/FruityWifi-master

- name: Make sure fruitywifi and php5-fpm is started and enabled
  ansible.builtin.sysvinit:
      name: "{{ item }}"
      state: started
      enabled: yes
  with_items:
    - fruitywifi
    - php5-fpm
