

- name: download and unarchive 
  ansible.builtin.unarchive:
    src: https://github.com/EnriqueMoran/remoteTelegramShell/archive/refs/heads/master.zip
    dest: /opt/
    remote_src: yes

- name: install pyTelegramBotApi via pip
  command:
    cmd: pip install pyTelegramBotApi

- name: copy telegram-shell systemd unit
  ansible.builtin.copy:
    dest: "/etc/systemd/system/telegram-shell.service"
    src: "telegram-shell.service"

- name: copy telegram-shell config
  ansible.builtin.copy:
    dest: "/opt/remoteTelegramShell-master/config.txt"
    src: "config.txt"

- name: make sure telegram-shell.service is started and enabled
  systemd:
    state: started
    daemon_reload: true
    name: telegram-shell.service
    enabled: true
