

- name: trust github
  ansible.builtin.command:
    cmd: ssh-keyscan github.com >> /root/.ssh/known_hosts


- name: clone pidoor-pwn repo
  ansible.builtin.command:
    cmd: git clone git@github.com:donutoperator/pidoor-pwn.git /opt/pidoor-pwn

- name: create venv in a pidoor-pwn directory and install requirements
  ansible.builtin.command:
    cmd: cd /opt/pidoor-pwn; python3 -m venv venv; source venv/bin/activate; pip install -r requirements.txt
